export const CREATE_POST_REQ = 'CREATE_POST_REQ'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'

export const GET_REQ_FAIL = 'GET_REQ_FAIL'
export const GET_POST_REQ = 'GET_POST_REQ'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'

export const DELETE_REQ_FAIL = 'DELETE_REQ_FAIL'
export const DELETE_POST_REQ = 'DELETE_POST_REQ'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'

export const POST_UPDATED_SUCCESS = 'POST_UPDATED_SUCCESS'

export const LOGIN_REQ = "LOGIN_REQ";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNUP_REQ = "SIGNUP_REQ";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";


export const SET_AUTH_REQ = 'SET_AUTH_REQ'
export const SET_AUTH_FAIL = 'SET_AUTH_FAIL'
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS'

export const GET_COMMENT_REQ = 'GET_COMMENT_REQ'
export const GET_COMMENT_REQ_FAIL = 'GET_COMMENT_REQ_FAIL'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'

export const GET_LIKES_REQ = 'GET_LIKES_REQ'
export const GET_LIKES_REQ_FAIL = 'GET_LIKES_REQ_FAIL'
export const GET_LIKES_SUCCESS = 'GET_LIKES_SUCCESS'

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const SET_POST_LIKE = 'SET_POST_LIKE'
export const UNSET_POST_LIKE = 'UNSET_POST_LIKE'
export const GET_POSTS = 'GET_POSTS'
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const GET_POST_LIKES = 'GET_POST_LIKES'
export const GET_COMMENTS = 'GET_COMMENTS'